Improve compatibility with new version of mysql
When running `mysqladmin -u root create biosqldb` with MySQL as 5.7.27-0 on Ubuntu 18.04, I got a warning saying  `mysqladmin: connect to server at 'localhost' failed
error: 'Access denied for user 'root'@'localhost''`. 

This problem seems to be that new mysql takes use of the `auth_socket` plugin if the password is left empty while installing. Answers from [stackoverflow](https://stackoverflow.com/questions/39281594/error-1698-28000-access-denied-for-user-rootlocalhost) suggest a password is required. Therefore, I changed the codes here for compatibility with the new version of mysql. 

**These codes were only tested on Ubuntu 18.04.**